name: update-and-deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1,4" # Run twice a week

permissions:
  contents: write

jobs:
  update-flake-lock:
    runs-on: oc-runner2
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Update flake.lock
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          nix flake update --commit-lock-file
          git push

      - name: Rebuild and switch
        run: sudo nixos-rebuild switch -L --flake .#oc-runner
